### ISSUE TITLE
Обнаружение фантомных устройств

### ISSUE THREAD

**Issue by subver55** [Zud71/elehant_meter#1]
Приветствую, попробовал использовать этот компонент, периодически появляются фантомные обнаруженные устройства, с которыми ничего нельзя сделать, что это может быть?
![image](https://github.com/Zud71/elehant_meter/assets/54464535/095b75c5-637f-4ed8-bace-d3ac8a90f558)
![image](https://github.com/Zud71/elehant_meter/assets/54464535/97331948-7038-432d-a09c-30f4320e34d4)

**Comment by Zud71** [comment]
Здравствуйте! Да, есть такое. Но я пока не совсем разобрался почему это происходит, пока просто игнорируйте все новые устройства.  Сейчас вроде у меня не выскакивает, но я вносил правки в код, но пока не выкладывал. На днях посмотрю.

**Comment by Zud71** [comment]
Обновите компонент ... должно помочь.

**Comment by fairslaven** [comment]
Скажите пожалуйста. Я добавил все по инструкции, но показания так и не отобразились, Подскажите в чем может быть проблема. Bluetoth proxi на ESP32/

**Comment by Zud71** [comment]
Какой именно esp32, полное именование? Что за тип счетчика?

**Comment by fairslaven** [comment]
Node MCU ESP32 38Pin, чип ESP-WROOM-32. Счетчик воды тарифный  СВТ-15 ЭЛЕХАНТ.

**Comment by Zud71** [comment]
Надо mac устройства, что он отдает и данные по Bluetooth. Для этого надо поставить приложение на телефон и перехватить трафик от счетчика. И откройте новый вопрос, эту ветку я закрою.

**Comment by evg26** [comment]
Все работает без ESP32

**Comment by evg26** [comment]
Возможно от физического адаптера bluetooth

**Comment by Zud71** [comment]
Данный компонент написан для работы не только с ESP32, а с любым bluetooth, хоть с физическими подключениями не проверялся.
