### ISSUE TITLE
Встроенный Bluetooth

### ISSUE THREAD

**Issue by PaveLGIL** [Zud71/elehant_meter#13]
Здравствуйте!
Подскажите пожалуйста, как можно использовать встроенный bluetooth adapter? Чтобы не делать через ESP32..
Я просто использую уже локальный bloetooth для добавления некоторых устаройств, но после установки интеграции через HACS, мне пишет no_devices_found.
![Screenshot 2024-10-24 at 14 06 36](https://github.com/user-attachments/assets/b44db493-82cb-4bf2-aa56-5b4adcb6c621)

Может могли бы пожалуйста помочь?

Bluetooth HA точно видит.
<img width="1018" alt="Screenshot 2024-10-23 at 22 45 37" src="https://github.com/user-attachments/assets/ef0b84a2-f8f8-41c2-ba5d-2ac9e535e80f">

**Comment by Zud71** [comment]
Интеграция должна работать с любым bluetooth адаптером. Возможно адаптер не поддерживает версию протокола, что использует счетчик или вы находитесь слишком далеко от счетчика.  Включите режим отладки и выложите сюда результат. 
logger:
  default: warning
  logs:
    homeassistant.components.bluetooth: debug
    custom_components.elehant_meter: debug

**Comment by PaveLGIL** [comment]
Да, все таки по дебагу вижу что интеграция работает, и ищет устройства..
[home-assistant_bluetooth_2024-10-27T13-05-12.197Z.log](https://github.com/user-attachments/files/17534048/home-assistant_bluetooth_2024-10-27T13-05-12.197Z.log)
Но почему-то не видит мой счетчик..(
Подскажите, может счетчик у меня не правильный?
Или на нем надо как-то включить Bluetooth?
Или может Bluetooth начинает данные передавать только когда они изменяются?
Могли бы мне чуть обьяснить этот вопрос?
У меня вот такой
![IMG_4019](https://github.com/user-attachments/assets/745273ce-d641-4ba1-a056-b1ee8e7fcd62)
![IMG_4020](https://github.com/user-attachments/assets/a4927882-ba59-4941-8281-7cad328b2c61)
![IMG_4021](https://github.com/user-attachments/assets/46d07aa6-3e56-4b64-9950-399db60fbdc8)

**Comment by Zud71** [comment]
Поставьте на телефон приложение типа nRF Connect, она покажет "сырые" данные от счетчика, может что-то производитель поменял. Выложите что она выдаст по счетчику.

**Comment by PaveLGIL** [comment]
А не подскажете что я должен увидеть, хотя бы примерно.. Имя девайся.. Просто все девайсы которые я не знаю подписаны как N/A.. Пытался их подключать, и те что подключаются, там ерунда какая-то.. Вообще ничего толкового..

**Comment by PaveLGIL** [comment]
Вот такой интересный разгоор у меня произошел с Элехант.. Это очень странно.. Много кто пишет в интернете что у счетчика есть Блютуз
![IMG_4022](https://github.com/user-attachments/assets/a4bb89e2-5361-4cb2-b4cd-cdf9967e4131)

**Comment by Zud71** [comment]
Интересно получается... Вы себе приложение поставили от Элехант? Показание оно как считывает?

**Comment by PaveLGIL** [comment]
Да, ставил, показанию меняются только через QR code

**Comment by PaveLGIL** [comment]
Прильно что вот нашел на WB этот счетчик конкретно с пометкой что есть Блютуз Элехант Счетчик газа СГБ-1,8 белый
https://global.wildberries.ru/product?card=185337445

Может у них какие-то разновидностиверсий, с блютуз и нет?

**Comment by Zud71** [comment]
Спасибо за информацию. Я вообще считал, что они все блюзные, а тут вот как. В исходном коде их приложения, вроде как этот тип счетчика так же анализируется по mac адресу, а mac адрес может быть только у блютуз устройств. 
Тогда исключу из списка совместимости, хоть ранее и писал, что поддерживаются, видимо буквы в наименовании попутал...

**Comment by Zud71** [comment]
> Прильно что вот нашел на WB этот счетчик конкретно с пометкой что есть Блютуз Элехант Счетчик газа СГБ-1,8 белый https://global.wildberries.ru/product?card=185337445
> 
> Может у них какие-то разновидностиверсий, с блютуз и нет?

На WB и прочих площадках что угодно могут писать... Я вообще покупал во всехинструментах с дисплеем, а пришел без него и в описании там была куча мала написана, на фото тоже.  Вся эта путаница в СГБ ... СГБД и т.д.

**Comment by PaveLGIL** [comment]
Да, я уже так и понял, позвонил тут в магазин от которого это пишут, так они сами не в курсе.. Эх.. Пойду искать другой счетчик.. Спасибо за помощь!

**Comment by Zud71** [comment]
С "Д" на конце я так понимаю модели без дисплея и поддержкой блютуз. А без Д это с экраном но без блютуз. Причем на счетчики воды там как-то по другому.

**Comment by PaveLGIL** [comment]
Походу да.. Но вроде как можно под них приобретать еще внешний экранчик, видел такую опцию

**Comment by PaveLGIL** [comment]
Купил СГБД 1.8, проверил, работает вообще отлично! Спасибо большое!
