### ISSUE TITLE
При попытке установить интеграцию выходит ошибка

### ISSUE THREAD

**Issue by whakru** [Zud71/elehant_meter#2]
![image](https://github.com/user-attachments/assets/7cd0551d-5e55-4272-b409-1288848b76d9)

**Comment by Zud71** [comment]
Вы скопировали как в инструкции, вы сервер перегрузили? Что пишется в системном логе?

**Comment by whakru** [comment]
> Вы скопировали как в инструкции, вы сервер перегрузили? Что пишется в системном логе?

Да в интеграциях же появился) сервер перезагружал.

**Comment by whakru** [comment]
> Вы скопировали как в инструкции, вы сервер перегрузили? Что пишется в системном логе?


```
Регистратор: aiohttp.server
Источник: /usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py:421
Первое сообщение: 17:59:16 (2 сообщений)
Последнее сообщение: 18:57:29

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 172, in post
    return await self._post_impl(request, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 179, in _post_impl
    return await super()._post_impl(request, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 84, in _post_impl
    result = await self._flow_mgr.async_init(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1267, in async_init
    flow, result = await self._async_init(flow_id, handler, context, data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1297, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 518, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/elehant_meter/config_flow.py", line 98, in async_step_user
    if adv.manufacturer_data:
       ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ElehantData' object has no attribute 'manufacturer_data'
```

**Comment by Zud71** [comment]
У вас что за счетчик?

**Comment by whakru** [comment]
> У вас что за счетчик?

![Screenshot_2024-07-15-19-30-21-057_ru ozon app android](https://github.com/user-attachments/assets/77d7503e-acb7-435c-8bb4-7276a3cddc9c)

**Comment by Zud71** [comment]
Попробуйте сейчас, скопируйте все файлы снова.

**Comment by whakru** [comment]
> Попробуйте сейчас, скопируйте все файлы снова.

Ошибку 500 не дает. теперь пишет no_devices_found. Но я не уверен что вобще мой esp работает как блютуз прокси.  Не подскажите как посмотреть устроиства которые он видит?

**Comment by Zud71** [comment]
Примерный код Прокси. 
```
substitutions:
  name: "esp32-bluetooth-elehant"
  friendly_name: Bluetooth Proxy Elehant
packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/esp32-generic.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

api:
  encryption:
    key: P6WgSzWsdassfsfsdfsdfsfsdfpNd5ANiCCQ=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms  
    window: 1100ms
    #duration: 10min
    active: false
    #continuous: true

bluetooth_proxy:
  active: true


logger:

```

В консоле Прокси будет писать о своих действиях. Если не пишет, по поиграться с секцией `logger: `

Еще в HA в конфигурации добавить.

```
logger:
  default: warning
  logs:
    homeassistant.components.bluetooth: debug
    custom_components.elehant_meter: debug
```

Будет в лог файл писать ...

**Comment by Zud71** [comment]
Что за модуль esp32  у вас?

**Comment by whakru** [comment]
> Что за модуль esp32 у вас?

![Screenshot_2024-07-16-00-00-23-930_com miui gallery](https://github.com/user-attachments/assets/a2666b38-4add-41dd-bcc8-3904589ebb18)

Честно сказать не могу понять как определить именно версию чипа... Типо там c2 c3 и тд. Может быть подскажите как это сделать?))

**Comment by Zud71** [comment]
https://ru.wikipedia.org/wiki/ESP32
Первый публичный вариант модуля от Espressif.[[11]](https://ru.wikipedia.org/wiki/ESP32#cite_note-EspressifESPWROOM32Datasheet-11) FCC Part 15.247 tested (FCC ID: 2AC7Z-ESPWROOM32).[[12]](https://ru.wikipedia.org/wiki/ESP32#cite_note-ESPWROOM32FCCTestReport-12) Based on ESP32-D0WDQ6 chip. Originally named «ESP32-WROOM-32».
Так же
https://dzen.ru/a/YygOUXbMMSjaAjcq

Версии c2 c3 - это архитектура RISC-V у вас точно не он.

**Comment by whakru** [comment]
> https://ru.wikipedia.org/wiki/ESP32 Первый публичный вариант модуля от Espressif.[[11]](https://ru.wikipedia.org/wiki/ESP32#cite_note-EspressifESPWROOM32Datasheet-11) FCC Part 15.247 tested (FCC ID: 2AC7Z-ESPWROOM32).[[12]](https://ru.wikipedia.org/wiki/ESP32#cite_note-ESPWROOM32FCCTestReport-12) Based on ESP32-D0WDQ6 chip. Originally named «ESP32-WROOM-32». Так же https://dzen.ru/a/YygOUXbMMSjaAjcq
> 
> Версии c2 c3 - это архитектура RISC-V у вас точно не он.

Detecting chip type... ESP32
Chip is ESP32-D0WD-V3 (revision v3.1)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz

**Comment by whakru** [comment]
Понял принял. Поискал все только такие видимо заказывал. Какую версию посоветуете? ESP32-C1 С2? 
Можно линк где брали себе). Кстати еще не большая просьба, сделайте обратную ссылку с гитхаба на статью orycan.

**Comment by Zud71** [comment]
У вас нормальная ESP, должно все работать, а вот RISC-V у меня работало очень плохо. Возможно несовместимость с Bluetooth
Поставьте на телефон приложение типа nRF Connect, она покажет "сырые" данные от счетчика, может что-то производитель поменял. Выложите что он выдаст по счетчику.

**Comment by fairslaven** [comment]
Здравствуйте. У меня та же самая проблема. Вот фотка после сканирование сети с помощью nRF Connect.
![Screenshot_2](https://github.com/user-attachments/assets/9b56e722-040f-4907-83d0-9d9ef24c6476)
![Screenshot_20](https://github.com/user-attachments/assets/696f3ed1-79ad-4a44-a033-43cae05a0cc7)

**Comment by Zud71** [comment]
Так. Все это странно.. буду разбираться. 
Что пишется если включить в HA
```
logger:
  default: warning
  logs:
    homeassistant.components.bluetooth: debug
    custom_components.elehant_meter: debug
```

**Comment by fairslaven** [comment]
Сейчас посмотрю. Еще при перезагрузки НА и проверки конфигурационого файла появляется пердупреждение: Предупреждения конфигурации
Platform error 'sensor' from integration 'elehant_meter' - Exception importing custom_components.elehant_meter.sensor

**Comment by fairslaven** [comment]
![1](https://github.com/user-attachments/assets/2c8639b6-718d-4242-903a-2ff5ff60f062)

**Comment by fairslaven** [comment]
[home-assistant_bluetooth_2024-07-18T08-35-48.524Z.log](https://github.com/user-attachments/files/16280196/home-assistant_bluetooth_2024-07-18T08-35-48.524Z.log)

**Comment by Zud71** [comment]
Спасибо! Будем разбираться, но наверное не на этой недели.

**Comment by whakru** [comment]
> Спасибо! Будем разбираться, но наверное не на этой недели.

Чуть позже скину свои данные.

**Comment by Zud71** [comment]
> [home-assistant_bluetooth_2024-07-18T08-35-48.524Z.log](https://github.com/user-attachments/files/16280196/home-assistant_bluetooth_2024-07-18T08-35-48.524Z.log)

По логу ... вы не обновили плагин, я заливал обновления. Скопируйте еще раз все файлы и перезагрузите НА. Очистите лог НА перед перезагрузкой. 

Компонент ESPHome в НА стоит?

**Comment by fairslaven** [comment]
Все сделал.
![Снимок7879](https://github.com/user-attachments/assets/f3085eb6-b3bb-455f-9156-f11ad296a76e)
[home-assistant_bluetooth_2024-07-19T08-25-54.353Z.log](https://github.com/user-attachments/files/16309419/home-assistant_bluetooth_2024-07-19T08-25-54.353Z.log)

**Comment by Zud71** [comment]
Буду разбираться, что-то там перемудрил ...

**Comment by fairslaven** [comment]
ОК. Спасибо.

**Comment by fairslaven** [comment]
Вы не ещё не разбирались?

**Comment by Zud71** [comment]
Обновите и попробуйте. НА перезапустите как обновите.

**Comment by fairslaven** [comment]
Здравствуйте. Счётчики добавились, но показаний нет.
![Screenshot_20240801-010446](https://github.com/user-attachments/assets/1f0283aa-e60f-4715-8a51-117df55b1b0d)

**Comment by fairslaven** [comment]
[error_log-1.txt](https://github.com/user-attachments/files/16447710/error_log-1.txt)

**Comment by Zud71** [comment]
Обновите sensor.py и желательно перегрузить НА.

**Comment by fairslaven** [comment]
Тоже самое.
[error_log.txt](https://github.com/user-attachments/files/16456451/error_log.txt)

**Comment by Zud71** [comment]
[sensor.zip](https://github.com/user-attachments/files/16457937/sensor.zip)
Замените этот файл и лог выложите когда ошибки опять будут.

**Comment by fairslaven** [comment]
Готово
[error_log-1.txt](https://github.com/user-attachments/files/16458871/error_log-1.txt)

**Comment by Zud71** [comment]
Так, попытка N.  Файл sensor.py копируем и пробуем ...

**Comment by fairslaven** [comment]
Пока что все тоже самое.
![Screenshot_20240801-194856](https://github.com/user-attachments/assets/167455b1-129c-41ec-89bf-0449f278328e)
[error_log.txt](https://github.com/user-attachments/files/16459583/error_log.txt)

**Comment by Zud71** [comment]
Да е-мое,  забыл заголовок ... еще разок
Надо будет перегрузить НА..

**Comment by fairslaven** [comment]
А надо в файле manifest и cons менять цифры на свой счётчик или нет?
![Screenshot_20240801-200119](https://github.com/user-attachments/assets/b3da2f57-88cc-42f6-9c5a-0ded5849332b)

**Comment by fairslaven** [comment]
Ещё раз скачать файлик sensor?

**Comment by Zud71** [comment]
Да. В манифесте и cons ничего менять не надо

**Comment by fairslaven** [comment]
Ооо. Все заработало. Спасибо большое!!! А все проблема была?
Скажите, а если ставить ещё один счётчик,на холодную воду, он добавится уже бес проблем или будут какие нибудь подводные камни?

**Comment by Zud71** [comment]
Основная проблема, что Python меня бесит и мне трудно понимать его синтаксис )))
Правки были в разных местах...
Вы пробуйте добавлять новые счетчики, проблемы будем решать по мере поступления.

**Comment by fairslaven** [comment]
Хорошо. Спасибо вам большое за помощь!!!

**Comment by fairslaven** [comment]
Уровень батарейки не отображается. Информация позже придет или её вообще не будет?

**Comment by Zud71** [comment]
Информации по батареи нет, добавлена функция на будущее

**Comment by fairslaven** [comment]
Хорошо понял.

**Comment by whakru** [comment]
```
2025-01-08 20:18:34.543 DEBUG (MainThread) [custom_components.elehant_meter.const] ElehantData init
2025-01-08 20:18:34.543 DEBUG (MainThread) [custom_components.elehant_meter.const] parse_mac: fe:7b:75:7c:4e:6a
2025-01-08 20:18:34.543 DEBUG (MainThread) [custom_components.elehant_meter.const] parse_mac Устройство не Елехант только (B0 или В1) , результат: fe
2025-01-08 20:18:34.543 DEBUG (MainThread) [custom_components.elehant_meter.const] parse_mac signValid: False
2025-01-08 20:18:34.543 DEBUG (MainThread) [custom_components.elehant_meter.const] parse_mac: 41:88:07:b8:bc:70
2025-01-08 20:18:34.543 DEBUG (MainThread) [custom_components.elehant_meter.const] parse_mac Устройство не Елехант только (B0 или В1) , результат: 41
2025-01-08 20:18:34.543 DEBUG (MainThread) [custom_components.elehant_meter.const] parse_mac: 49:6d:21:ab:fc:b0
2025-01-08 20:18:34.543 DEBUG (MainThread) [custom_components.elehant_meter.const] parse_mac Устройство не Елехант только (B0 или В1) , результат: 49
2025-01-08 20:18:34.543 DEBUG (MainThread) [custom_components.elehant_meter.const] parse_mac: 70:76:13:59:3e:00
2025-01-08 20:18:34.543 DEBUG (MainThread) [custom_components.elehant_meter.const] parse_mac Устройство не Елехант только (B0 или В1) , результат: 70
2025-01-08 20:18:34.543 DEBUG (MainThread) [custom_components.elehant_meter.const] parse_mac: 4c:2f:bb:95:22:1c
2025-01-08 20:18:34.543 DEBUG (MainThread) [custom_components.elehant_meter.const] parse_mac Устройство не Елехант только (B0 или В1) , результат: 4c
```

Видимо моя есп не видит счетчика хотя в nrfConnect я его вижу...
Подскажите конкретную модель есп32 которую приобрести) Можно ссылочку Али, озон там и тд)

**Comment by Zud71** [comment]
Не надо писать в закрытую ветку!
Откройте новую тему. Напишите точную модель счетчика. Пришлите что выдает nrfConnect. Напишите какая ESP32 у вас сейчас. 
ESP32 NODEMCU 30pin DEVKIT V1 - должна работать без проблем. Вы можете USB bluetooth любой поставить.
