### ISSUE TITLE
Неиспользуемая конфигурация YAML

### ISSUE THREAD

**Issue by evg26** [Zud71/elehant_meter#3]
1 проблема доступна для устранения

Неиспользуемая конфигурация YAML для интеграции elehant_meter
Невозможно настроить elehant_meter sensor, добавив platform: elehant_meter в конфигурацию sensor. Пожалуйста, ознакомьтесь с документацией для получения дополнительной информации о том, как настроить эту интеграцию.

Чтобы решить эту проблему:

Удалите platform: elehant_meter из конфигурации sensor: в файле конфигурации YAML.
Перезапустите Home Assistant.
Пример фрагмента, который следует удалить:

sensor:
  - platform: elehant_meter
Ошибка - 24.09.2024

**Comment by Zud71** [comment]
У меня есть только ошибка:
The elehant_meter platform for the sensor integration does not support platform setup. Please remove it from your config.
Но она не влияет на работу.

**Comment by evg26** [comment]
ошибка исчезла после удаления:
 sensor:
  - platform: elehant_meter
