### ISSUE TITLE
Номер Счетчика

### ISSUE THREAD

**Issue by evg26** [Zud71/elehant_meter#4]
Номер счетчика не соответствует

**Comment by Zud71** [comment]
Что за тип счетчика? Как вы определили, что номер не соответствует?

**Comment by evg26** [comment]
Счетчики СВД-15


На счетчиках номера другие

**Comment by Zud71** [comment]
Поставьте на телефон приложение типа nRF Connect или ей подобную, она покажет "сырые" данные от счетчика. Так же напишите реальные номера счетчика с сопоставлением, как они определяются в НА.

**Comment by evg26** [comment]
35711 - 0101247
35723 - 0101259

**Comment by Zud71** [comment]
Без данных от счетчика представленная вами информация не говорит ни о чем.

**Comment by evg26** [comment]
Name: n/a
Address: B0:01:02:01:8B:7F
RSSI: -95 dBm
Last advertisement packet:
Raw data: 0x14FFFFFF80ED960102017F8B01733200007FBE0821

**Comment by evg26** [comment]
Name: n/a

RSSI: -90 dBm
Last advertisement packet:



Name: n/a

RSSI: -95 dBm
Last advertisement packet:

**Comment by Zud71** [comment]
Обновите файл const.py. Удалите устройства, должны определится правильно.

**Comment by evg26** [comment]
После обновления определяются правильно

**Comment by evg26** [comment]
При добавлении карточки:

В карточке:

Может вместо MAC адреса выводить номер счетчика.
При добавлении не плохо было бы иметь возможность указывать какая вода "холодная, горячая"

**Comment by evg26** [comment]
Подскажите что нужно для отображения уровня батареи?

**Comment by Zud71** [comment]
Карточку вы можете изменить как вам хочется и написать, что хотите. 
Уровень батареи добавлен на будущее, сейчас такую информацию счетчики не отдают.

**Comment by evg26** [comment]
В приложении Элехант отображается батарея

**Comment by Zud71** [comment]
Создайте новый Запрос и приложите текущее данные от счетчика и значение уровня батарее в приложении.

**Comment by evg26** [comment]
Значения нет, только картинка

**Comment by evg26** [comment]
101247 - "battery" : 127
101259 -  "battery" : 124

**Comment by Zud71** [comment]
Не лепите все проблемы в одну ветку обсуждений. Проблема с номером счетчика закрыта. 
Как вы получили значение батареи?
Сейчас идут доработки, позже будут выложены, там будет батарея и название счетчика ...
