### ISSUE TITLE
Значек

### ISSUE THREAD

**Issue by evg26** [Zud71/elehant_meter#8]
Может добавите значек к интеграции
![cLXTdSQ2NAU](https://github.com/user-attachments/assets/a558ecf9-0f68-4453-965d-04a33690cd95)

**Comment by Zud71** [comment]
Значок я просто так добавить не могу, его надо интегрировать в HA путем https://github.com/home-assistant/brands
Займусь когда-нибудь ... Либо вы можете это сделать.

**Comment by evg26** [comment]
Не понятно куда значок поместить

**Comment by Zud71** [comment]
Необходимо выполнить требования, что написаны по ссылке и направить запрос на добавления своего значка в систему.  Значок может быть взят только по данному пути  https://brands.home-assistant.io/elehant_meter/

**Comment by evg26** [comment]
![icon](https://github.com/user-attachments/assets/add5f37e-6385-4910-9c3a-20997389c242)
Значек согласно требованиям. Как направить запрос не понимаю.

**Comment by Zud71** [comment]
Как добавить - эту тему надо изучать, я пока не знаю

**Comment by dudanov** [comment]
Привет. Добавлен в этом [PR](https://github.com/home-assistant/brands/pull/6108). Используйте домен `elehant`.
