### ISSUE TITLE
Показания счетчиков

### ISSUE THREAD

**Issue by evg26** [Zud71/elehant_meter#9]
Может показания счетчиков выводить в таком виде как в приложении, целая часть и + отдельно значения после запятой.

**Comment by Zud71** [comment]
Не совсем понятно как это будет выглядеть. Мне вместо запятой + поставить?

**Comment by evg26** [comment]
Вот так выглядит в приложении



### хотя есть и другой вид


Наверное это и не к чему, просто мне надо были целые показания для автоматизации передаци показаний в ТСЖ. Можно закрыть этот вопрос.

**Comment by Zud71** [comment]
Это все визуализация, а данная интеграция просто собирает данные. Как дальше обрабатывать полученные данные и как выводить каждый решает сам.
